# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CMD_BSMC_Game.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CMD_BSMC_Game.proto',
  package='CMD_BSMC',
  serialized_pb='\n\x13\x43MD_BSMC_Game.proto\x12\x08\x43MD_BSMC\"9\n\x10\x43MD_SUB_S_CONFIG\x12\x11\n\tcoin_list\x18\x01 \x03(\x05\x12\x12\n\nbrick_list\x18\x02 \x03(\x05\"2\n\x0e\x43MD_UserInfo_S\x12\r\n\x05score\x18\x01 \x01(\x03\x12\x11\n\tnick_name\x18\x02 \x01(\x0c\"i\n\x0e\x43MD_GameInfo_S\x12\r\n\x05level\x18\x01 \x01(\x05\x12\r\n\x05\x62rick\x18\x02 \x01(\x05\x12\x1a\n\x12private_prize_pool\x18\x03 \x01(\x05\x12\x1d\n\x15private_prize_pool_up\x18\x04 \x01(\x05\"\"\n\rCMD_SUB_C_BET\x12\x11\n\tbet_score\x18\x01 \x01(\x05\".\n\x0fMSG_DropGemInfo\x12\x0b\n\x03\x63ol\x18\x01 \x01(\x05\x12\x0e\n\x06gem_id\x18\x02 \x01(\x05\">\n\x0bMSG_GemLink\x12\x0e\n\x06gem_id\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x05\x12\x10\n\x08pos_list\x18\x03 \x03(\x05\"C\n\x0cMSG_GemLinks\x12\r\n\x05score\x18\x01 \x01(\x05\x12$\n\x05links\x18\x02 \x03(\x0b\x32\x15.CMD_BSMC.MSG_GemLink\"\xa5\x01\n\x0bMSG_GemData\x12\x11\n\tbet_score\x18\x01 \x01(\x05\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x11\n\tget_score\x18\x03 \x01(\x05\x12\x11\n\tinit_data\x18\x04 \x03(\x05\x12%\n\x05links\x18\x05 \x03(\x0b\x32\x16.CMD_BSMC.MSG_GemLinks\x12(\n\x05\x64rops\x18\x06 \x03(\x0b\x32\x19.CMD_BSMC.MSG_DropGemInfo\"U\n\rCMD_SUB_S_BET\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\x0c\x12#\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x15.CMD_BSMC.MSG_GemData\"\x11\n\x0f\x43MD_SUB_C_AWARD\"&\n\tMSG_AWARD\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"j\n\x0f\x43MD_SUB_S_AWARD\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\x0c\x12\x11\n\taward_idx\x18\x03 \x01(\x05\x12#\n\x06\x61wards\x18\x04 \x03(\x0b\x32\x13.CMD_BSMC.MSG_AWARD\"9\n\x10\x43MD_SysMessage_S\x12\x10\n\x08sys_type\x18\x01 \x01(\r\x12\x13\n\x0bsys_message\x18\x02 \x01(\x0c\x42\x02H\x03')




_CMD_SUB_S_CONFIG = _descriptor.Descriptor(
  name='CMD_SUB_S_CONFIG',
  full_name='CMD_BSMC.CMD_SUB_S_CONFIG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coin_list', full_name='CMD_BSMC.CMD_SUB_S_CONFIG.coin_list', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brick_list', full_name='CMD_BSMC.CMD_SUB_S_CONFIG.brick_list', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=90,
)


_CMD_USERINFO_S = _descriptor.Descriptor(
  name='CMD_UserInfo_S',
  full_name='CMD_BSMC.CMD_UserInfo_S',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='CMD_BSMC.CMD_UserInfo_S.score', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nick_name', full_name='CMD_BSMC.CMD_UserInfo_S.nick_name', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=92,
  serialized_end=142,
)


_CMD_GAMEINFO_S = _descriptor.Descriptor(
  name='CMD_GameInfo_S',
  full_name='CMD_BSMC.CMD_GameInfo_S',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='CMD_BSMC.CMD_GameInfo_S.level', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brick', full_name='CMD_BSMC.CMD_GameInfo_S.brick', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='private_prize_pool', full_name='CMD_BSMC.CMD_GameInfo_S.private_prize_pool', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='private_prize_pool_up', full_name='CMD_BSMC.CMD_GameInfo_S.private_prize_pool_up', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=144,
  serialized_end=249,
)


_CMD_SUB_C_BET = _descriptor.Descriptor(
  name='CMD_SUB_C_BET',
  full_name='CMD_BSMC.CMD_SUB_C_BET',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bet_score', full_name='CMD_BSMC.CMD_SUB_C_BET.bet_score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=251,
  serialized_end=285,
)


_MSG_DROPGEMINFO = _descriptor.Descriptor(
  name='MSG_DropGemInfo',
  full_name='CMD_BSMC.MSG_DropGemInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='col', full_name='CMD_BSMC.MSG_DropGemInfo.col', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gem_id', full_name='CMD_BSMC.MSG_DropGemInfo.gem_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=287,
  serialized_end=333,
)


_MSG_GEMLINK = _descriptor.Descriptor(
  name='MSG_GemLink',
  full_name='CMD_BSMC.MSG_GemLink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gem_id', full_name='CMD_BSMC.MSG_GemLink.gem_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='CMD_BSMC.MSG_GemLink.score', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos_list', full_name='CMD_BSMC.MSG_GemLink.pos_list', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=335,
  serialized_end=397,
)


_MSG_GEMLINKS = _descriptor.Descriptor(
  name='MSG_GemLinks',
  full_name='CMD_BSMC.MSG_GemLinks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='CMD_BSMC.MSG_GemLinks.score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='links', full_name='CMD_BSMC.MSG_GemLinks.links', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=399,
  serialized_end=466,
)


_MSG_GEMDATA = _descriptor.Descriptor(
  name='MSG_GemData',
  full_name='CMD_BSMC.MSG_GemData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bet_score', full_name='CMD_BSMC.MSG_GemData.bet_score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='CMD_BSMC.MSG_GemData.size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_score', full_name='CMD_BSMC.MSG_GemData.get_score', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='init_data', full_name='CMD_BSMC.MSG_GemData.init_data', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='links', full_name='CMD_BSMC.MSG_GemData.links', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='drops', full_name='CMD_BSMC.MSG_GemData.drops', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=469,
  serialized_end=634,
)


_CMD_SUB_S_BET = _descriptor.Descriptor(
  name='CMD_SUB_S_BET',
  full_name='CMD_BSMC.CMD_SUB_S_BET',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CMD_BSMC.CMD_SUB_S_BET.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='CMD_BSMC.CMD_SUB_S_BET.err_msg', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='CMD_BSMC.CMD_SUB_S_BET.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=636,
  serialized_end=721,
)


_CMD_SUB_C_AWARD = _descriptor.Descriptor(
  name='CMD_SUB_C_AWARD',
  full_name='CMD_BSMC.CMD_SUB_C_AWARD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=723,
  serialized_end=740,
)


_MSG_AWARD = _descriptor.Descriptor(
  name='MSG_AWARD',
  full_name='CMD_BSMC.MSG_AWARD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CMD_BSMC.MSG_AWARD.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='CMD_BSMC.MSG_AWARD.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=742,
  serialized_end=780,
)


_CMD_SUB_S_AWARD = _descriptor.Descriptor(
  name='CMD_SUB_S_AWARD',
  full_name='CMD_BSMC.CMD_SUB_S_AWARD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CMD_BSMC.CMD_SUB_S_AWARD.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='CMD_BSMC.CMD_SUB_S_AWARD.err_msg', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='award_idx', full_name='CMD_BSMC.CMD_SUB_S_AWARD.award_idx', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='awards', full_name='CMD_BSMC.CMD_SUB_S_AWARD.awards', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=782,
  serialized_end=888,
)


_CMD_SYSMESSAGE_S = _descriptor.Descriptor(
  name='CMD_SysMessage_S',
  full_name='CMD_BSMC.CMD_SysMessage_S',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sys_type', full_name='CMD_BSMC.CMD_SysMessage_S.sys_type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sys_message', full_name='CMD_BSMC.CMD_SysMessage_S.sys_message', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=890,
  serialized_end=947,
)

_MSG_GEMLINKS.fields_by_name['links'].message_type = _MSG_GEMLINK
_MSG_GEMDATA.fields_by_name['links'].message_type = _MSG_GEMLINKS
_MSG_GEMDATA.fields_by_name['drops'].message_type = _MSG_DROPGEMINFO
_CMD_SUB_S_BET.fields_by_name['data'].message_type = _MSG_GEMDATA
_CMD_SUB_S_AWARD.fields_by_name['awards'].message_type = _MSG_AWARD
DESCRIPTOR.message_types_by_name['CMD_SUB_S_CONFIG'] = _CMD_SUB_S_CONFIG
DESCRIPTOR.message_types_by_name['CMD_UserInfo_S'] = _CMD_USERINFO_S
DESCRIPTOR.message_types_by_name['CMD_GameInfo_S'] = _CMD_GAMEINFO_S
DESCRIPTOR.message_types_by_name['CMD_SUB_C_BET'] = _CMD_SUB_C_BET
DESCRIPTOR.message_types_by_name['MSG_DropGemInfo'] = _MSG_DROPGEMINFO
DESCRIPTOR.message_types_by_name['MSG_GemLink'] = _MSG_GEMLINK
DESCRIPTOR.message_types_by_name['MSG_GemLinks'] = _MSG_GEMLINKS
DESCRIPTOR.message_types_by_name['MSG_GemData'] = _MSG_GEMDATA
DESCRIPTOR.message_types_by_name['CMD_SUB_S_BET'] = _CMD_SUB_S_BET
DESCRIPTOR.message_types_by_name['CMD_SUB_C_AWARD'] = _CMD_SUB_C_AWARD
DESCRIPTOR.message_types_by_name['MSG_AWARD'] = _MSG_AWARD
DESCRIPTOR.message_types_by_name['CMD_SUB_S_AWARD'] = _CMD_SUB_S_AWARD
DESCRIPTOR.message_types_by_name['CMD_SysMessage_S'] = _CMD_SYSMESSAGE_S

class CMD_SUB_S_CONFIG(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMD_SUB_S_CONFIG

  # @@protoc_insertion_point(class_scope:CMD_BSMC.CMD_SUB_S_CONFIG)

class CMD_UserInfo_S(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMD_USERINFO_S

  # @@protoc_insertion_point(class_scope:CMD_BSMC.CMD_UserInfo_S)

class CMD_GameInfo_S(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMD_GAMEINFO_S

  # @@protoc_insertion_point(class_scope:CMD_BSMC.CMD_GameInfo_S)

class CMD_SUB_C_BET(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMD_SUB_C_BET

  # @@protoc_insertion_point(class_scope:CMD_BSMC.CMD_SUB_C_BET)

class MSG_DropGemInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG_DROPGEMINFO

  # @@protoc_insertion_point(class_scope:CMD_BSMC.MSG_DropGemInfo)

class MSG_GemLink(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG_GEMLINK

  # @@protoc_insertion_point(class_scope:CMD_BSMC.MSG_GemLink)

class MSG_GemLinks(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG_GEMLINKS

  # @@protoc_insertion_point(class_scope:CMD_BSMC.MSG_GemLinks)

class MSG_GemData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG_GEMDATA

  # @@protoc_insertion_point(class_scope:CMD_BSMC.MSG_GemData)

class CMD_SUB_S_BET(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMD_SUB_S_BET

  # @@protoc_insertion_point(class_scope:CMD_BSMC.CMD_SUB_S_BET)

class CMD_SUB_C_AWARD(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMD_SUB_C_AWARD

  # @@protoc_insertion_point(class_scope:CMD_BSMC.CMD_SUB_C_AWARD)

class MSG_AWARD(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG_AWARD

  # @@protoc_insertion_point(class_scope:CMD_BSMC.MSG_AWARD)

class CMD_SUB_S_AWARD(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMD_SUB_S_AWARD

  # @@protoc_insertion_point(class_scope:CMD_BSMC.CMD_SUB_S_AWARD)

class CMD_SysMessage_S(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMD_SYSMESSAGE_S

  # @@protoc_insertion_point(class_scope:CMD_BSMC.CMD_SysMessage_S)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003')
# @@protoc_insertion_point(module_scope)
