# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmd_msdmx.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmd_msdmx.proto',
  package='',
  serialized_pb='\n\x0f\x63md_msdmx.proto\"9\n\x10\x63md_sub_s_config\x12\x11\n\tcoin_list\x18\x01 \x03(\x05\x12\x12\n\nbrick_list\x18\x02 \x03(\x05\".\n\x0e\x63md_gameinfo_s\x12\r\n\x05level\x18\x01 \x01(\x05\x12\r\n\x05\x62rick\x18\x02 \x01(\x05\"\"\n\rcmd_sub_c_bet\x12\x11\n\tbet_score\x18\x01 \x01(\x05\".\n\x0fmsg_dropgeminfo\x12\x0b\n\x03\x63ol\x18\x01 \x01(\x05\x12\x0e\n\x06gem_id\x18\x02 \x01(\x05\">\n\x0bmsg_gemlink\x12\x0e\n\x06gem_id\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x05\x12\x10\n\x08pos_list\x18\x03 \x03(\x05\":\n\x0cmsg_gemlinks\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x1b\n\x05links\x18\x02 \x03(\x0b\x32\x0c.msg_gemlink\"\xcc\x01\n\x0bmsg_gemdata\x12\x11\n\tbet_score\x18\x01 \x01(\x05\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x11\n\tget_score\x18\x03 \x01(\x05\x12\x11\n\tinit_data\x18\x04 \x03(\x05\x12\x1c\n\x05links\x18\x05 \x03(\x0b\x32\r.msg_gemlinks\x12\x1f\n\x05\x64rops\x18\x06 \x03(\x0b\x32\x10.msg_dropgeminfo\x12\r\n\x05level\x18\x07 \x01(\x05\x12\x13\n\x0btotal_score\x18\x08 \x01(\x01\x12\x13\n\x0b\x64wDropTimes\x18\t \x01(\x05\"Q\n\rcmd_sub_s_bet\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x1a\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x0c.msg_gemdata\x12\x10\n\x08sys_type\x18\x03 \x01(\r\"\x11\n\x0f\x63md_sub_c_award\"&\n\tmsg_award\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"T\n\x0f\x63md_sub_s_award\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x11\n\taward_idx\x18\x02 \x01(\x05\x12\x1a\n\x06\x61wards\x18\x03 \x03(\x0b\x32\n.msg_award\"9\n\x10\x63md_sysmessage_s\x12\x10\n\x08sys_type\x18\x01 \x01(\r\x12\x13\n\x0bsys_message\x18\x02 \x01(\x0c\x42\x02H\x03')




_CMD_SUB_S_CONFIG = _descriptor.Descriptor(
  name='cmd_sub_s_config',
  full_name='cmd_sub_s_config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coin_list', full_name='cmd_sub_s_config.coin_list', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brick_list', full_name='cmd_sub_s_config.brick_list', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=76,
)


_CMD_GAMEINFO_S = _descriptor.Descriptor(
  name='cmd_gameinfo_s',
  full_name='cmd_gameinfo_s',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='cmd_gameinfo_s.level', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brick', full_name='cmd_gameinfo_s.brick', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=78,
  serialized_end=124,
)


_CMD_SUB_C_BET = _descriptor.Descriptor(
  name='cmd_sub_c_bet',
  full_name='cmd_sub_c_bet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bet_score', full_name='cmd_sub_c_bet.bet_score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=126,
  serialized_end=160,
)


_MSG_DROPGEMINFO = _descriptor.Descriptor(
  name='msg_dropgeminfo',
  full_name='msg_dropgeminfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='col', full_name='msg_dropgeminfo.col', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gem_id', full_name='msg_dropgeminfo.gem_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=162,
  serialized_end=208,
)


_MSG_GEMLINK = _descriptor.Descriptor(
  name='msg_gemlink',
  full_name='msg_gemlink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gem_id', full_name='msg_gemlink.gem_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='msg_gemlink.score', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos_list', full_name='msg_gemlink.pos_list', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=210,
  serialized_end=272,
)


_MSG_GEMLINKS = _descriptor.Descriptor(
  name='msg_gemlinks',
  full_name='msg_gemlinks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='msg_gemlinks.score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='links', full_name='msg_gemlinks.links', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=274,
  serialized_end=332,
)


_MSG_GEMDATA = _descriptor.Descriptor(
  name='msg_gemdata',
  full_name='msg_gemdata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bet_score', full_name='msg_gemdata.bet_score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='msg_gemdata.size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_score', full_name='msg_gemdata.get_score', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='init_data', full_name='msg_gemdata.init_data', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='links', full_name='msg_gemdata.links', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='drops', full_name='msg_gemdata.drops', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='msg_gemdata.level', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_score', full_name='msg_gemdata.total_score', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dwDropTimes', full_name='msg_gemdata.dwDropTimes', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=335,
  serialized_end=539,
)


_CMD_SUB_S_BET = _descriptor.Descriptor(
  name='cmd_sub_s_bet',
  full_name='cmd_sub_s_bet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='cmd_sub_s_bet.error_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='cmd_sub_s_bet.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sys_type', full_name='cmd_sub_s_bet.sys_type', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=541,
  serialized_end=622,
)


_CMD_SUB_C_AWARD = _descriptor.Descriptor(
  name='cmd_sub_c_award',
  full_name='cmd_sub_c_award',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=624,
  serialized_end=641,
)


_MSG_AWARD = _descriptor.Descriptor(
  name='msg_award',
  full_name='msg_award',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='msg_award.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='msg_award.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=643,
  serialized_end=681,
)


_CMD_SUB_S_AWARD = _descriptor.Descriptor(
  name='cmd_sub_s_award',
  full_name='cmd_sub_s_award',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='cmd_sub_s_award.error_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='award_idx', full_name='cmd_sub_s_award.award_idx', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='awards', full_name='cmd_sub_s_award.awards', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=683,
  serialized_end=767,
)


_CMD_SYSMESSAGE_S = _descriptor.Descriptor(
  name='cmd_sysmessage_s',
  full_name='cmd_sysmessage_s',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sys_type', full_name='cmd_sysmessage_s.sys_type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sys_message', full_name='cmd_sysmessage_s.sys_message', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=769,
  serialized_end=826,
)

_MSG_GEMLINKS.fields_by_name['links'].message_type = _MSG_GEMLINK
_MSG_GEMDATA.fields_by_name['links'].message_type = _MSG_GEMLINKS
_MSG_GEMDATA.fields_by_name['drops'].message_type = _MSG_DROPGEMINFO
_CMD_SUB_S_BET.fields_by_name['data'].message_type = _MSG_GEMDATA
_CMD_SUB_S_AWARD.fields_by_name['awards'].message_type = _MSG_AWARD
DESCRIPTOR.message_types_by_name['cmd_sub_s_config'] = _CMD_SUB_S_CONFIG
DESCRIPTOR.message_types_by_name['cmd_gameinfo_s'] = _CMD_GAMEINFO_S
DESCRIPTOR.message_types_by_name['cmd_sub_c_bet'] = _CMD_SUB_C_BET
DESCRIPTOR.message_types_by_name['msg_dropgeminfo'] = _MSG_DROPGEMINFO
DESCRIPTOR.message_types_by_name['msg_gemlink'] = _MSG_GEMLINK
DESCRIPTOR.message_types_by_name['msg_gemlinks'] = _MSG_GEMLINKS
DESCRIPTOR.message_types_by_name['msg_gemdata'] = _MSG_GEMDATA
DESCRIPTOR.message_types_by_name['cmd_sub_s_bet'] = _CMD_SUB_S_BET
DESCRIPTOR.message_types_by_name['cmd_sub_c_award'] = _CMD_SUB_C_AWARD
DESCRIPTOR.message_types_by_name['msg_award'] = _MSG_AWARD
DESCRIPTOR.message_types_by_name['cmd_sub_s_award'] = _CMD_SUB_S_AWARD
DESCRIPTOR.message_types_by_name['cmd_sysmessage_s'] = _CMD_SYSMESSAGE_S

class cmd_sub_s_config(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMD_SUB_S_CONFIG

  # @@protoc_insertion_point(class_scope:cmd_sub_s_config)

class cmd_gameinfo_s(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMD_GAMEINFO_S

  # @@protoc_insertion_point(class_scope:cmd_gameinfo_s)

class cmd_sub_c_bet(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMD_SUB_C_BET

  # @@protoc_insertion_point(class_scope:cmd_sub_c_bet)

class msg_dropgeminfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG_DROPGEMINFO

  # @@protoc_insertion_point(class_scope:msg_dropgeminfo)

class msg_gemlink(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG_GEMLINK

  # @@protoc_insertion_point(class_scope:msg_gemlink)

class msg_gemlinks(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG_GEMLINKS

  # @@protoc_insertion_point(class_scope:msg_gemlinks)

class msg_gemdata(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG_GEMDATA

  # @@protoc_insertion_point(class_scope:msg_gemdata)

class cmd_sub_s_bet(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMD_SUB_S_BET

  # @@protoc_insertion_point(class_scope:cmd_sub_s_bet)

class cmd_sub_c_award(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMD_SUB_C_AWARD

  # @@protoc_insertion_point(class_scope:cmd_sub_c_award)

class msg_award(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG_AWARD

  # @@protoc_insertion_point(class_scope:msg_award)

class cmd_sub_s_award(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMD_SUB_S_AWARD

  # @@protoc_insertion_point(class_scope:cmd_sub_s_award)

class cmd_sysmessage_s(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMD_SYSMESSAGE_S

  # @@protoc_insertion_point(class_scope:cmd_sysmessage_s)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003')
# @@protoc_insertion_point(module_scope)
